### PR TITLE
NativeScript 7 Support

### PR DESCRIPTION
**Pull request by lochstar**
I've migrated this plugin to NS7 as I require it in a commercial project.

The demo app is working for Android & iOS.

I had troubles with Angular support as I don't use Angular myself. I believe I have the plugin packaging correctly but I'm not sure how to import it properly in demo-ng.

I'm also not sure if you planned to move this to NativeScrit/plugins.

### CODE REVIEW

**Comment by bradmartin** [comment]
Nice work @lochstar, can you delete the `.migration-backup` directories in the PR?

**Comment by bradmartin** [comment]
For now, we'll prob leave this plugin here where it is, maybe in some time we can migrate it to the `@nativescript/plugins` scope and then deprecate this version 👍  but for now it's good enough to get NS7 support pushed out.

**Review by bradmartin — COMMENTED** [review]
So far everything looks good at quick glance, just delete the .migration-backup directory and we'll merge it, and I'll go ahead and confirm everything and get a new major version pushed out ASAP 💯

**Comment by lochstar** [comment]
Done! Didn't mean to check that in!

**Comment by bradmartin** [comment]
Thanks again, just needs some minor changes for the native class `extends`, I'll get that pushed up soon and published out.

**Pull request merged**
